product_domain_name="test_domain"
environment_type="test"
operations_aws_account_number="123456789012"
application_aws_account_number="210987654321"
vpc_id = "vpc-XXXXXX"
subnet_id = "subnet-ZXC"
jenkins_config_repo_url = "ssh://git@github.com:kentrikos/env-config.git"
jenkins_dns_domain_hosted_zone_ID = "ABCDEFGHIJKLMN"
