# TESTING ENVIRONMENT CONFIGURATION:
image: golang

before_script:
  - apt-get update
  - apt-get install -y unzip jq
  - wget https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
  - unzip terraform_0.11.14_linux_amd64.zip
  - mv terraform /bin
  - chmod +x /bin/terraform
  - go get github.com/gruntwork-io/terratest/modules/terraform
  - go get github.com/stretchr/testify/assert


## JOBS:
# Check Terraform formatting:
job-format:
  script:
    - terraform fmt -check

# Run terraform init:
job-terratest-terraform-init:
  script:
    - cd test
    - go test -v -run TestTerraformInit

# Run terraform validate:
job-format:
  script:
    - terraform validate -var-file test/terraform.tfvars
