# TESTING ENVIRONMENT CONFIGURATION:
image: golang

before_script:
  - apt-get update
  - apt-get install unzip
  - wget https://releases.hashicorp.com/terraform/0.12.1/terraform_0.12.1_linux_amd64.zip
  - unzip terraform_0.12.1_linux_amd64.zip
  - mv terraform /bin
  - chmod +x /bin/terraform
  - go get github.com/gruntwork-io/terratest/modules/terraform
  - go get github.com/stretchr/testify/assert


## JOBS:
# Check Terraform formatting:
job-format:
  script:
    - terraform fmt -check

# Run terraform init and plan:
job-terraform-init-and-plan:
  script:
    - cd test
    - go test -v -run TestTerraformInitPlan
